import type { Adapter, RouteManifest, AdapterConfig, AdapterBuildResult } from "../types.js";

/**
 * Generate JS code string for the AWS Lambda handler.
 * Converts APIGatewayProxyEvent to Web Request and Response back to APIGatewayProxyResult.
 */
export function generateLambdaHandler(manifest: RouteManifest): string {
  const routeEntries = manifest.routes
    .map((r) => {
      const isDynamic = r.segments.some(
        (s) => s.type === "dynamic" || s.type === "catch-all"
      );
      return `  { pattern: ${JSON.stringify(r.pattern)}, dynamic: ${isDynamic} }`;
    })
    .join(",\n");

  const lines: string[] = [
    "// AWS Lambda handler — generated by vais-kit",
    "const routes = [",
    routeEntries,
    "];",
    "",
    "function matchRoute(pathname) {",
    "  for (const route of routes) {",
    "    if (route.pattern === pathname) return route;",
    "    const escaped = route.pattern.replace(/[.+?^${}()|\\\\]/g, '\\\\$&');",
    "    const regexStr = '^' + escaped.replace(/\\[([^\\]]+)\\]/g, '([^/]+)') + '$';",
    "    const regex = new RegExp(regexStr);",
    "    if (regex.test(pathname)) return route;",
    "  }",
    "  return null;",
    "}",
    "",
    "function renderPage() {",
    "  return '<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n  <meta charset=\"UTF-8\">\\n  <title>Page</title>\\n</head>\\n<body>\\n  <div id=\"app\"></div>\\n  <script type=\"module\" src=\"/client.js\"></script>\\n</body>\\n</html>';",
    "}",
    "",
    "/**",
    " * Convert APIGatewayProxyEvent to Web API Request.",
    " */",
    "function eventToRequest(event) {",
    "  const method = event.httpMethod || 'GET';",
    "  const path = event.path || '/';",
    "  const queryString = event.queryStringParameters",
    "    ? '?' + new URLSearchParams(event.queryStringParameters).toString()",
    "    : '';",
    "  const url = `https://lambda.amazonaws.com${path}${queryString}`;",
    "  const headers = new Headers(event.headers || {});",
    "  const body = event.body ? (event.isBase64Encoded ? Buffer.from(event.body, 'base64') : event.body) : undefined;",
    "  return new Request(url, { method, headers, body: method !== 'GET' && method !== 'HEAD' ? body : undefined });",
    "}",
    "",
    "/**",
    " * Convert Web API Response to APIGatewayProxyResult.",
    " */",
    "async function responseToResult(response) {",
    "  const body = await response.text();",
    "  const headers = {};",
    "  response.headers.forEach((value, key) => { headers[key] = value; });",
    "  return {",
    "    statusCode: response.status,",
    "    headers,",
    "    body,",
    "    isBase64Encoded: false,",
    "  };",
    "}",
    "",
    "/**",
    " * Lambda handler entry point.",
    " */",
    "export async function handler(event, context) {",
    "  const request = eventToRequest(event);",
    "  const url = new URL(request.url);",
    "  const pathname = url.pathname;",
    "",
    "  const route = matchRoute(pathname);",
    "  if (route) {",
    "    const html = renderPage();",
    "    const response = new Response(html, {",
    "      status: 200,",
    "      headers: { 'Content-Type': 'text/html; charset=utf-8' },",
    "    });",
    "    return responseToResult(response);",
    "  }",
    "",
    "  const notFound = new Response('Not Found', {",
    "    status: 404,",
    "    headers: { 'Content-Type': 'text/plain' },",
    "  });",
    "  return responseToResult(notFound);",
    "}",
  ];

  return lines.join("\n") + "\n";
}

/**
 * Generate AWS SAM template.yaml for Lambda deployment.
 */
export function generateSamTemplate(config: AdapterConfig): string {
  const memorySize = 512;
  const timeout = 30;

  return (
    "AWSTemplateFormatVersion: '2010-09-09'\n" +
    "Transform: AWS::Serverless-2016-10-31\n" +
    "Description: vais-kit AWS Lambda deployment\n" +
    "\n" +
    "Globals:\n" +
    "  Function:\n" +
    `    MemorySize: ${memorySize}\n` +
    `    Timeout: ${timeout}\n` +
    "\n" +
    "Resources:\n" +
    "  VaisAppFunction:\n" +
    "    Type: AWS::Serverless::Function\n" +
    "    Properties:\n" +
    "      Handler: handler.handler\n" +
    "      Runtime: nodejs20.x\n" +
    "      CodeUri: ./\n" +
    "      Events:\n" +
    "        ApiGateway:\n" +
    "          Type: Api\n" +
    "          Properties:\n" +
    "            Path: /{proxy+}\n" +
    "            Method: ANY\n" +
    "        ApiGatewayRoot:\n" +
    "          Type: Api\n" +
    "          Properties:\n" +
    "            Path: /\n" +
    "            Method: ANY\n"
  );
}

/**
 * Create the AWS Lambda adapter.
 * Generates Lambda handler wrapper code and SAM template.yaml.
 */
export function createAwsLambdaAdapter(): Adapter {
  return {
    name: "aws-lambda",

    async build(
      manifest: RouteManifest,
      config: AdapterConfig
    ): Promise<AdapterBuildResult> {
      const outputDir = "dist";
      const files: string[] = [];
      const generatedFiles: Record<string, string> = {};

      // Generate Lambda handler
      const handlerCode = generateLambdaHandler(manifest);
      const handlerPath = `${outputDir}/handler.js`;
      files.push(handlerPath);
      generatedFiles[handlerPath] = handlerCode;

      // Generate SAM template.yaml
      const samTemplate = generateSamTemplate(config);
      const templatePath = `${outputDir}/template.yaml`;
      files.push(templatePath);
      generatedFiles[templatePath] = samTemplate;

      const result: AdapterBuildResult & {
        generatedFiles?: Record<string, string>;
      } = {
        outputDir,
        files,
        generatedFiles,
      };

      return result;
    },
  };
}
