import type { Adapter, RouteManifest, AdapterConfig, AdapterBuildResult } from "../types.js";

/**
 * Generate JS code string for the Bun server entry point.
 * Uses Bun.serve with Web API (Request/Response) natively.
 */
export function generateBunServerEntry(manifest: RouteManifest, port = 3000): string {
  const routeEntries = manifest.routes
    .map((r) => {
      const isDynamic = r.segments.some(
        (s) => s.type === "dynamic" || s.type === "catch-all"
      );
      return `  { pattern: ${JSON.stringify(r.pattern)}, dynamic: ${isDynamic} }`;
    })
    .join(",\n");

  const lines: string[] = [
    "// Bun server entry point — generated by vais-kit",
    `const PORT = ${port};`,
    "",
    "const routes = [",
    routeEntries,
    "];",
    "",
    "function matchRoute(pathname) {",
    "  for (const route of routes) {",
    "    if (route.pattern === pathname) return route;",
    "    const escaped = route.pattern.replace(/[.+?^${}()|\\\\]/g, '\\\\$&');",
    "    const regexStr = '^' + escaped.replace(/\\[([^\\]]+)\\]/g, '([^/]+)') + '$';",
    "    const regex = new RegExp(regexStr);",
    "    if (regex.test(pathname)) return route;",
    "  }",
    "  return null;",
    "}",
    "",
    "function renderPage() {",
    "  return '<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n  <meta charset=\"UTF-8\">\\n  <title>Page</title>\\n</head>\\n<body>\\n  <div id=\"app\"></div>\\n  <script type=\"module\" src=\"/client.js\"></script>\\n</body>\\n</html>';",
    "}",
    "",
    "Bun.serve({",
    "  port: PORT,",
    "  async fetch(request) {",
    "    const url = new URL(request.url);",
    "    const pathname = url.pathname;",
    "",
    "    // Match against routes",
    "    const route = matchRoute(pathname);",
    "    if (route) {",
    "      const html = renderPage();",
    "      return new Response(html, {",
    "        status: 200,",
    "        headers: { 'Content-Type': 'text/html; charset=utf-8' },",
    "      });",
    "    }",
    "",
    "    // 404",
    "    return new Response('Not Found', {",
    "      status: 404,",
    "      headers: { 'Content-Type': 'text/plain' },",
    "    });",
    "  },",
    "});",
    "",
    `console.log(\`Bun server listening on http://localhost:\${PORT}\`);`,
  ];

  return lines.join("\n") + "\n";
}

/**
 * Create the Bun adapter.
 * Generates server.js entry point using Bun.serve.
 */
export function createBunAdapter(): Adapter {
  return {
    name: "bun",

    async build(
      manifest: RouteManifest,
      config: AdapterConfig
    ): Promise<AdapterBuildResult> {
      const port = config.port ?? 3000;
      const outputDir = "dist";
      const files: string[] = [];
      const generatedFiles: Record<string, string> = {};

      // Generate server entry point
      const serverEntry = generateBunServerEntry(manifest, port);
      const serverPath = `${outputDir}/server.js`;
      files.push(serverPath);
      generatedFiles[serverPath] = serverEntry;

      const result: AdapterBuildResult & {
        generatedFiles?: Record<string, string>;
      } = {
        outputDir,
        files,
        generatedFiles,
      };

      return result;
    },
  };
}
