import type { Adapter, RouteManifest, AdapterConfig, AdapterBuildResult } from "../types.js";

/**
 * Generate JS code string for the Cloudflare Workers entry point.
 * The generated code exports a default fetch handler that performs
 * route matching and SSR rendering, with static asset serving.
 */
export function generateWorkerEntry(manifest: RouteManifest): string {
  const routeEntries = manifest.routes
    .map((r) => {
      const isDynamic = r.segments.some(
        (s) => s.type === "dynamic" || s.type === "catch-all"
      );
      return `  { pattern: ${JSON.stringify(r.pattern)}, dynamic: ${isDynamic} }`;
    })
    .join(",\n");

  // Build the code as an array of lines to avoid regex-in-template-literal issues
  const lines: string[] = [
    "// Cloudflare Workers entry point — generated by vais-kit",
    "const routes = [",
    routeEntries,
    "];",
    "",
    "function matchRoute(pathname) {",
    "  for (const route of routes) {",
    "    if (route.pattern === pathname) return route;",
    "    const escaped = route.pattern.replace(/[.+?^${}()|\\\\]/g, '\\\\$&');",
    "    const regexStr = '^' + escaped.replace(/\\[([^\\]]+)\\]/g, '([^/]+)') + '$';",
    "    const regex = new RegExp(regexStr);",
    "    if (regex.test(pathname)) return route;",
    "  }",
    "  return null;",
    "}",
    "",
    "async function serveStaticAsset(request, env) {",
    "  if (env.__STATIC_CONTENT) {",
    "    try {",
    "      const url = new URL(request.url);",
    "      const key = url.pathname.replace(/^\\//, '') || 'index.html';",
    "      const asset = await env.__STATIC_CONTENT.get(key, { type: 'arrayBuffer' });",
    "      if (asset) {",
    "        const ext = key.split('.').pop() || '';",
    "        const contentTypes = {",
    "          html: 'text/html; charset=utf-8',",
    "          js: 'application/javascript',",
    "          css: 'text/css',",
    "          json: 'application/json',",
    "          png: 'image/png',",
    "          jpg: 'image/jpeg',",
    "          svg: 'image/svg+xml',",
    "        };",
    "        const contentType = contentTypes[ext] || 'application/octet-stream';",
    "        return new Response(asset, {",
    "          headers: { 'Content-Type': contentType },",
    "        });",
    "      }",
    "    } catch {",
    "      // asset not found, continue to SSR",
    "    }",
    "  }",
    "  return null;",
    "}",
    "",
    "function renderPage(pathname) {",
    "  return '<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n  <meta charset=\"UTF-8\">\\n  <title>Page</title>\\n</head>\\n<body>\\n  <div id=\"app\"></div>\\n  <script type=\"module\" src=\"/client.js\"></script>\\n</body>\\n</html>';",
    "}",
    "",
    "export default {",
    "  async fetch(request, env, ctx) {",
    "    const url = new URL(request.url);",
    "    const pathname = url.pathname;",
    "",
    "    // Try static asset first",
    "    const staticResponse = await serveStaticAsset(request, env);",
    "    if (staticResponse) return staticResponse;",
    "",
    "    // Match against routes",
    "    const route = matchRoute(pathname);",
    "    if (route) {",
    "      const html = renderPage(pathname);",
    "      return new Response(html, {",
    "        status: 200,",
    "        headers: { 'Content-Type': 'text/html; charset=utf-8' },",
    "      });",
    "    }",
    "",
    "    // 404",
    "    return new Response('Not Found', {",
    "      status: 404,",
    "      headers: { 'Content-Type': 'text/plain' },",
    "    });",
    "  },",
    "};",
  ];

  return lines.join("\n") + "\n";
}

/**
 * Generate a wrangler.toml configuration string for Cloudflare Workers.
 */
export function generateWranglerConfig(_config: AdapterConfig): string {
  const name = "vais-app";
  const compatibilityDate = "2024-01-01";

  return (
    `name = "${name}"\n` +
    `compatibility_date = "${compatibilityDate}"\n` +
    "\n" +
    "[site]\n" +
    'bucket = "./_assets"\n' +
    'entry-point = "."\n'
  );
}

/**
 * Create the Cloudflare Workers adapter.
 * Generates _worker.js entry point, _assets/ directory listing,
 * and wrangler.toml template.
 */
export function createCloudflareAdapter(): Adapter {
  return {
    name: "cloudflare",

    async build(
      manifest: RouteManifest,
      config: AdapterConfig
    ): Promise<AdapterBuildResult> {
      const outputDir = "dist";
      const files: string[] = [];
      const generatedFiles: Record<string, string> = {};

      // Generate _worker.js entry point
      const workerEntry = generateWorkerEntry(manifest);
      const workerPath = `${outputDir}/_worker.js`;
      files.push(workerPath);
      generatedFiles[workerPath] = workerEntry;

      // Generate static asset entries in _assets/
      for (const route of manifest.routes) {
        if (route.page) {
          const hasDynamic = route.segments.some(
            (s) => s.type === "dynamic" || s.type === "catch-all"
          );

          if (!hasDynamic && !route.apiRoute) {
            const assetPath =
              route.pattern === "/"
                ? `${outputDir}/_assets/index.html`
                : `${outputDir}/_assets${route.pattern}/index.html`;
            files.push(assetPath);
            generatedFiles[assetPath] =
              "<!DOCTYPE html>\n" +
              '<html lang="en">\n' +
              "<head>\n" +
              '  <meta charset="UTF-8">\n' +
              '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n' +
              "  <title>Page</title>\n" +
              "</head>\n" +
              "<body>\n" +
              '  <div id="app"></div>\n' +
              '  <script type="module" src="/client.js"></script>\n' +
              "</body>\n" +
              "</html>\n";
          }
        }
      }

      // Generate wrangler.toml
      const wranglerConfig = generateWranglerConfig(config);
      const wranglerPath = `${outputDir}/wrangler.toml`;
      files.push(wranglerPath);
      generatedFiles[wranglerPath] = wranglerConfig;

      const result: AdapterBuildResult & {
        generatedFiles?: Record<string, string>;
      } = {
        outputDir,
        files,
        generatedFiles,
      };

      return result;
    },
  };
}
