import type { Adapter, RouteManifest, AdapterConfig, AdapterBuildResult } from "../types.js";

/**
 * Generate JS code string for the Deno Deploy server entry point.
 * Uses Deno.serve with Web API (Request/Response) natively.
 */
export function generateDenoServerEntry(manifest: RouteManifest): string {
  const routeEntries = manifest.routes
    .map((r) => {
      const isDynamic = r.segments.some(
        (s) => s.type === "dynamic" || s.type === "catch-all"
      );
      return `  { pattern: ${JSON.stringify(r.pattern)}, dynamic: ${isDynamic} }`;
    })
    .join(",\n");

  const lines: string[] = [
    "// Deno Deploy entry point — generated by vais-kit",
    "const routes = [",
    routeEntries,
    "];",
    "",
    "function matchRoute(pathname) {",
    "  for (const route of routes) {",
    "    if (route.pattern === pathname) return route;",
    "    const escaped = route.pattern.replace(/[.+?^${}()|\\\\]/g, '\\\\$&');",
    "    const regexStr = '^' + escaped.replace(/\\[([^\\]]+)\\]/g, '([^/]+)') + '$';",
    "    const regex = new RegExp(regexStr);",
    "    if (regex.test(pathname)) return route;",
    "  }",
    "  return null;",
    "}",
    "",
    "function renderPage() {",
    "  return '<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n  <meta charset=\"UTF-8\">\\n  <title>Page</title>\\n</head>\\n<body>\\n  <div id=\"app\"></div>\\n  <script type=\"module\" src=\"/client.js\"></script>\\n</body>\\n</html>';",
    "}",
    "",
    "Deno.serve(async (request) => {",
    "  const url = new URL(request.url);",
    "  const pathname = url.pathname;",
    "",
    "  // Match against routes",
    "  const route = matchRoute(pathname);",
    "  if (route) {",
    "    const html = renderPage();",
    "    return new Response(html, {",
    "      status: 200,",
    "      headers: { 'Content-Type': 'text/html; charset=utf-8' },",
    "    });",
    "  }",
    "",
    "  // 404",
    "  return new Response('Not Found', {",
    "    status: 404,",
    "    headers: { 'Content-Type': 'text/plain' },",
    "  });",
    "});",
  ];

  return lines.join("\n") + "\n";
}

/**
 * Generate deno.json configuration for Deno Deploy.
 */
export function generateDenoConfig(): string {
  return JSON.stringify(
    {
      tasks: {
        start: "deno run --allow-net --allow-read server.ts",
        dev: "deno run --watch --allow-net --allow-read server.ts",
      },
      importMap: "./import_map.json",
      compilerOptions: {
        lib: ["deno.window"],
      },
    },
    null,
    2
  ) + "\n";
}

/**
 * Create the Deno Deploy adapter.
 * Generates server.ts entry point using Deno.serve and deno.json config.
 */
export function createDenoAdapter(): Adapter {
  return {
    name: "deno",

    async build(
      manifest: RouteManifest,
      _config: AdapterConfig
    ): Promise<AdapterBuildResult> {
      const outputDir = "dist";
      const files: string[] = [];
      const generatedFiles: Record<string, string> = {};

      // Generate server entry point
      const serverEntry = generateDenoServerEntry(manifest);
      const serverPath = `${outputDir}/server.ts`;
      files.push(serverPath);
      generatedFiles[serverPath] = serverEntry;

      // Generate deno.json config
      const denoConfig = generateDenoConfig();
      const denoConfigPath = `${outputDir}/deno.json`;
      files.push(denoConfigPath);
      generatedFiles[denoConfigPath] = denoConfig;

      const result: AdapterBuildResult & {
        generatedFiles?: Record<string, string>;
      } = {
        outputDir,
        files,
        generatedFiles,
      };

      return result;
    },
  };
}
