import type { Adapter, RouteManifest, AdapterConfig, AdapterBuildResult } from "../types.js";

/**
 * Generate JS code string for the Netlify Functions handler.
 */
export function generateNetlifyHandler(manifest: RouteManifest): string {
  const routeEntries = manifest.routes
    .map((r) => {
      const isDynamic = r.segments.some(
        (s) => s.type === "dynamic" || s.type === "catch-all"
      );
      return `  { pattern: ${JSON.stringify(r.pattern)}, dynamic: ${isDynamic} }`;
    })
    .join(",\n");

  const lines: string[] = [
    "// Netlify Functions handler — generated by vais-kit",
    "const routes = [",
    routeEntries,
    "];",
    "",
    "function matchRoute(pathname) {",
    "  for (const route of routes) {",
    "    if (route.pattern === pathname) return route;",
    "    const escaped = route.pattern.replace(/[.+?^${}()|\\\\]/g, '\\\\$&');",
    "    const regexStr = '^' + escaped.replace(/\\[([^\\]]+)\\]/g, '([^/]+)') + '$';",
    "    const regex = new RegExp(regexStr);",
    "    if (regex.test(pathname)) return route;",
    "  }",
    "  return null;",
    "}",
    "",
    "function renderPage() {",
    "  return '<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n  <meta charset=\"UTF-8\">\\n  <title>Page</title>\\n</head>\\n<body>\\n  <div id=\"app\"></div>\\n  <script type=\"module\" src=\"/client.js\"></script>\\n</body>\\n</html>';",
    "}",
    "",
    "export const handler = async (event, context) => {",
    "  const pathname = event.path || '/';",
    "",
    "  const route = matchRoute(pathname);",
    "  if (route) {",
    "    return {",
    "      statusCode: 200,",
    "      headers: { 'Content-Type': 'text/html; charset=utf-8' },",
    "      body: renderPage(),",
    "    };",
    "  }",
    "",
    "  return {",
    "    statusCode: 404,",
    "    headers: { 'Content-Type': 'text/plain' },",
    "    body: 'Not Found',",
    "  };",
    "};",
  ];

  return lines.join("\n") + "\n";
}

/**
 * Generate netlify.toml configuration file.
 */
export function generateNetlifyToml(): string {
  return (
    "[build]\n" +
    '  command = "npm run build"\n' +
    '  publish = "dist/static"\n' +
    '  functions = "dist/functions"\n' +
    "\n" +
    "[[redirects]]\n" +
    '  from = "/api/*"\n' +
    '  to = "/.netlify/functions/handler"\n' +
    "  status = 200\n" +
    "\n" +
    "[[redirects]]\n" +
    '  from = "/*"\n' +
    '  to = "/index.html"\n' +
    "  status = 200\n"
  );
}

/**
 * Generate _redirects file for SPA fallback.
 */
export function generateRedirects(): string {
  return "/*    /index.html   200\n";
}

/**
 * Create the Netlify adapter.
 * Generates Netlify Functions handler, netlify.toml, and _redirects for SPA fallback.
 */
export function createNetlifyAdapter(): Adapter {
  return {
    name: "netlify",

    async build(
      manifest: RouteManifest,
      _config: AdapterConfig
    ): Promise<AdapterBuildResult> {
      const outputDir = "dist";
      const files: string[] = [];
      const generatedFiles: Record<string, string> = {};

      // Generate Netlify Functions handler
      const handlerCode = generateNetlifyHandler(manifest);
      const handlerPath = `${outputDir}/functions/handler.js`;
      files.push(handlerPath);
      generatedFiles[handlerPath] = handlerCode;

      // Generate netlify.toml
      const netlifyToml = generateNetlifyToml();
      const tomlPath = `${outputDir}/netlify.toml`;
      files.push(tomlPath);
      generatedFiles[tomlPath] = netlifyToml;

      // Generate _redirects for SPA fallback
      const redirects = generateRedirects();
      const redirectsPath = `${outputDir}/static/_redirects`;
      files.push(redirectsPath);
      generatedFiles[redirectsPath] = redirects;

      const result: AdapterBuildResult & {
        generatedFiles?: Record<string, string>;
      } = {
        outputDir,
        files,
        generatedFiles,
      };

      return result;
    },
  };
}
