/**
 * dts.ts
 *
 * .d.ts auto-generation for .vaisx component type exports.
 *
 * Generates a TypeScript declaration file that:
 *  - Exports a Props type for the component.
 *  - Exports a default type representing the component itself.
 *  - Preserves any named type/interface exports found in the script block.
 */

import { parseScriptBlocks } from "./parser.js";
import { extractProps, type PropDefinition } from "./props.js";

// ─── Public types ────────────────────────────────────────────────────────────

export interface DtsGenerationOptions {
  /** Absolute or relative path to the .vaisx file (used as module identifier). */
  filename: string;
  /** Raw .vaisx source content. */
  source: string;
  /**
   * Name to use for the component in the generated declarations.
   * Defaults to the base filename without extension, PascalCased.
   */
  componentName?: string;
}

export interface DtsGenerationResult {
  /** Generated .d.ts content as a string. */
  dts: string;
  /** The component name used in the declarations. */
  componentName: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Convert a filename such as "my-button.vaisx" to "MyButton". */
function toPascalCase(filename: string): string {
  // Strip directory and extension.
  const base = filename.replace(/.*[\\/]/, "").replace(/\.[^.]+$/, "");
  return base
    .split(/[-_\s]+/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

/** Indent each line of `text` by `n` spaces. */
function indent(text: string, n: number): string {
  const pad = " ".repeat(n);
  return text
    .split("\n")
    .map((l) => (l.trim() ? pad + l : l))
    .join("\n");
}

/** Build the Props interface body from an array of PropDefinitions. */
function buildPropsInterface(props: PropDefinition[]): string {
  if (props.length === 0) {
    return "export interface Props {}\n";
  }

  const members = props
    .map((p) => {
      const optional = p.required ? "" : "?";
      const defaultComment = p.default !== undefined ? ` // default: ${p.default}` : "";
      return `  ${p.name}${optional}: ${p.type};${defaultComment}`;
    })
    .join("\n");

  return `export interface Props {\n${members}\n}\n`;
}

/**
 * Regex patterns that identify exported declarations in TS source.
 * We capture: export interface Foo, export type Foo, export const Foo,
 * export function foo, export class Foo, export enum Foo.
 */
const EXPORT_DECLARATION_RE =
  /^export\s+(?:(?:default\s+)?(?:interface|type|class|enum|function|const|let|var)\s+(\w+))/gm;

/**
 * Collect the names of all top-level exports in the TypeScript source
 * (excluding `export default`).
 */
function collectNamedExports(tsSource: string): string[] {
  const names: string[] = [];
  EXPORT_DECLARATION_RE.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = EXPORT_DECLARATION_RE.exec(tsSource)) !== null) {
    if (m[1]) names.push(m[1]);
  }
  return [...new Set(names)];
}

/**
 * Extract `export type { ... }` or `export { ... }` re-exports.
 */
const REEXPORT_RE = /export\s+(?:type\s+)?\{([^}]+)\}/gm;

function collectReExports(tsSource: string): string[] {
  const names: string[] = [];
  REEXPORT_RE.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = REEXPORT_RE.exec(tsSource)) !== null) {
    const items = m[1].split(",").map((s) => {
      const parts = s.trim().split(/\s+as\s+/);
      return (parts[1] ?? parts[0]).trim();
    });
    names.push(...items.filter(Boolean));
  }
  return names;
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Generate a `.d.ts` declaration file for a `.vaisx` component.
 *
 * The generated file declares:
 *  - A `Props` interface derived from `defineProps<T>()`.
 *  - Any named types/interfaces already exported by the script block.
 *  - A default export typed as a component function `(props: Props) => void`.
 */
export function generateDts(options: DtsGenerationOptions): DtsGenerationResult {
  const { filename, source } = options;

  const componentName = options.componentName ?? toPascalCase(filename);

  const { scriptBlocks, hasTypeScript } = parseScriptBlocks(source);
  const tsSource = scriptBlocks.map((b) => b.source).join("\n");

  // Extract props.
  const { props, rawGeneric } = extractProps(source);

  const lines: string[] = [];

  // File header.
  lines.push(`// Auto-generated by @vaisx/typescript`);
  lines.push(`// Source: ${filename}`);
  lines.push(``);

  if (!hasTypeScript) {
    // No TS block — emit a minimal declaration.
    lines.push(`export interface Props {}`);
    lines.push(``);
    lines.push(`declare const ${componentName}: (props?: Props) => void;`);
    lines.push(`export default ${componentName};`);
    return { dts: lines.join("\n") + "\n", componentName };
  }

  // 1. Emit Props interface.
  if (rawGeneric && rawGeneric.trim().startsWith("{")) {
    // Inline object type — emit directly.
    lines.push(buildPropsInterface(props).trimEnd());
  } else if (rawGeneric) {
    // Named type reference — re-export it as Props alias.
    lines.push(`export type Props = ${rawGeneric};`);
  } else {
    lines.push(`export interface Props {}`);
  }
  lines.push(``);

  // 2. Re-emit named exports from the script block that aren't Props.
  const namedExports = [
    ...collectNamedExports(tsSource),
    ...collectReExports(tsSource),
  ].filter((n) => n !== "Props" && n !== "default");

  if (namedExports.length > 0) {
    lines.push(`// Named exports from <script lang="ts">`);
    for (const name of namedExports) {
      lines.push(`export type { ${name} };`);
    }
    lines.push(``);
  }

  // 3. Emit the component default export.
  lines.push(`/** ${componentName} component */`);
  lines.push(`declare function ${componentName}(props: Props): void;`);
  lines.push(`export default ${componentName};`);

  return { dts: lines.join("\n") + "\n", componentName };
}

/**
 * Generate only the Props interface declaration string for a component.
 * Useful when embedding into a larger .d.ts file.
 */
export function generatePropsDeclaration(
  source: string,
  componentName?: string
): string {
  const { props, rawGeneric } = extractProps(source);
  const name = componentName ?? "Component";

  if (rawGeneric && !rawGeneric.trim().startsWith("{")) {
    return `export type ${name}Props = ${rawGeneric};`;
  }

  return buildPropsInterface(props)
    .replace("export interface Props", `export interface ${name}Props`)
    .trimEnd();
}
