/**
 * snapshot — utilities for snapshot-testing VaisX component output.
 *
 * Works with Vitest's built-in snapshot system (expect().toMatchSnapshot()).
 * The helpers here normalise / pretty-print HTML so snapshots are readable
 * and deterministic across runs.
 */

// ---------------------------------------------------------------------------
// HTML normalisation
// ---------------------------------------------------------------------------

/**
 * Normalise an HTML string so that minor formatting differences don't cause
 * snapshot failures.  Strips leading/trailing whitespace on each line and
 * collapses consecutive blank lines.
 */
export function normaliseHtml(html: string): string {
  return html
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join("\n");
}

// ---------------------------------------------------------------------------
// Pretty-print (basic indenting)
// ---------------------------------------------------------------------------

/**
 * Very lightweight HTML pretty-printer — indents opening/closing tags so
 * snapshot output is human-readable.
 *
 * Note: this is intentionally simple and handles only the subset of HTML
 * generated by VaisX compiled components.  For production-grade formatting
 * consider using a dedicated library.
 */
export function prettyHtml(html: string): string {
  const VOID_ELEMENTS = new Set([
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
  ]);

  let indent = 0;
  const INDENT = "  ";
  const lines: string[] = [];

  // Simple token-based approach: split on tag boundaries.
  const tokens = html.split(/(<[^>]+>)/g).filter(Boolean);

  for (const token of tokens) {
    if (token.startsWith("</")) {
      // Closing tag — dedent first.
      indent = Math.max(0, indent - 1);
      lines.push(`${INDENT.repeat(indent)}${token}`);
    } else if (token.startsWith("<")) {
      // Opening tag.
      const tagName = (token.match(/^<([a-z][a-z0-9-]*)/i)?.[1] ?? "").toLowerCase();
      lines.push(`${INDENT.repeat(indent)}${token}`);
      if (!VOID_ELEMENTS.has(tagName) && !token.endsWith("/>")) {
        indent += 1;
      }
    } else {
      // Text node — only emit if non-empty.
      const text = token.trim();
      if (text) {
        lines.push(`${INDENT.repeat(indent)}${text}`);
      }
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// toMatchSnapshot helpers
// ---------------------------------------------------------------------------

/**
 * Return the pretty-printed innerHTML of a container for use with Vitest
 * snapshot assertions.
 *
 * @example
 * ```ts
 * const { container } = render(MyComponent);
 * expect(snapshotHtml(container)).toMatchSnapshot();
 * ```
 */
export function snapshotHtml(container: HTMLElement): string {
  return prettyHtml(container.innerHTML);
}

/**
 * Return the outer HTML of a specific element — useful when you only want to
 * snapshot a sub-tree rather than the whole container.
 *
 * @example
 * ```ts
 * const { getByTestId } = render(MyComponent);
 * expect(snapshotElement(getByTestId('card'))).toMatchSnapshot();
 * ```
 */
export function snapshotElement(element: HTMLElement): string {
  return prettyHtml(element.outerHTML);
}

// ---------------------------------------------------------------------------
// ComponentSnapshot type  (for storing captured snapshots in-memory)
// ---------------------------------------------------------------------------

export interface ComponentSnapshot {
  /** Name / description of this snapshot. */
  name: string;
  /** The captured HTML. */
  html: string;
  /** ISO timestamp of when the snapshot was taken. */
  timestamp: string;
}

/**
 * Capture a named snapshot of a container's current state.
 * Returned objects can be stored and compared programmatically.
 */
export function captureSnapshot(
  name: string,
  container: HTMLElement,
): ComponentSnapshot {
  return {
    name,
    html: snapshotHtml(container),
    timestamp: new Date().toISOString(),
  };
}

/**
 * Assert that two previously captured snapshots are identical.
 * Throws a descriptive error if they differ.
 */
export function assertSnapshotMatch(
  a: ComponentSnapshot,
  b: ComponentSnapshot,
): void {
  if (a.html !== b.html) {
    throw new Error(
      `Snapshot mismatch between "${a.name}" and "${b.name}".\n` +
        `--- ${a.name} ---\n${a.html}\n\n` +
        `+++ ${b.name} ---\n${b.html}`,
    );
  }
}
