import { describe, it, expect } from "vitest";
import { generateDts, generatePropsDeclaration } from "../src/dts.js";

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const INLINE_PROPS_VAISX = `
<script lang="ts">
const props = defineProps<{
  title: string;
  count?: number;
}>();
</script>
`;

const NAMED_TYPE_VAISX = `
<script lang="ts">
interface CardProps {
  header: string;
  body?: string;
}
const props = defineProps<CardProps>();
</script>
`;

const WITH_EXPORTS_VAISX = `
<script lang="ts">
export type ButtonVariant = 'primary' | 'secondary';
export interface ButtonProps { variant: ButtonVariant; label: string }
const props = defineProps<ButtonProps>();
</script>
`;

const NO_TS_VAISX = `
<template><div>hi</div></template>
`;

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("generateDts — header", () => {
  it("includes the auto-generated comment", () => {
    const { dts } = generateDts({ filename: "Button.vaisx", source: INLINE_PROPS_VAISX });
    expect(dts).toContain("Auto-generated by @vaisx/typescript");
  });

  it("includes the source filename in the header", () => {
    const { dts } = generateDts({ filename: "Button.vaisx", source: INLINE_PROPS_VAISX });
    expect(dts).toContain("Button.vaisx");
  });
});

describe("generateDts — component name", () => {
  it("derives PascalCase component name from filename", () => {
    const { componentName } = generateDts({ filename: "my-button.vaisx", source: INLINE_PROPS_VAISX });
    expect(componentName).toBe("MyButton");
  });

  it("allows overriding the component name", () => {
    const { componentName, dts } = generateDts({
      filename: "my-button.vaisx",
      source: INLINE_PROPS_VAISX,
      componentName: "CustomButton",
    });
    expect(componentName).toBe("CustomButton");
    expect(dts).toContain("CustomButton");
  });
});

describe("generateDts — Props interface", () => {
  it("emits a Props interface for inline generic objects", () => {
    const { dts } = generateDts({ filename: "Button.vaisx", source: INLINE_PROPS_VAISX });
    expect(dts).toContain("export interface Props");
    expect(dts).toContain("title: string");
  });

  it("marks required props without the ? modifier", () => {
    const { dts } = generateDts({ filename: "Button.vaisx", source: INLINE_PROPS_VAISX });
    // "title: string" — no ? before the colon.
    expect(dts).toMatch(/title:\s*string/);
  });

  it("marks optional props with the ? modifier", () => {
    const { dts } = generateDts({ filename: "Button.vaisx", source: INLINE_PROPS_VAISX });
    expect(dts).toMatch(/count\?:\s*number/);
  });

  it("emits a Props type alias for named type reference", () => {
    const { dts } = generateDts({ filename: "Card.vaisx", source: NAMED_TYPE_VAISX });
    expect(dts).toContain("export type Props = CardProps");
  });
});

describe("generateDts — default export", () => {
  it("declares the component as a default export function", () => {
    const { dts, componentName } = generateDts({
      filename: "Button.vaisx",
      source: INLINE_PROPS_VAISX,
    });
    expect(dts).toContain(`declare function ${componentName}`);
    expect(dts).toContain(`export default ${componentName}`);
  });
});

describe("generateDts — no TS block", () => {
  it("generates a minimal declaration when there is no TS block", () => {
    const { dts } = generateDts({ filename: "Simple.vaisx", source: NO_TS_VAISX });
    expect(dts).toContain("export interface Props {}");
    expect(dts).toContain("export default");
  });
});

describe("generatePropsDeclaration", () => {
  it("generates a named Props interface", () => {
    const decl = generatePropsDeclaration(INLINE_PROPS_VAISX, "MyCard");
    expect(decl).toContain("export interface MyCardProps");
    expect(decl).toContain("title: string");
  });

  it("uses a default component name when none provided", () => {
    const decl = generatePropsDeclaration(INLINE_PROPS_VAISX);
    expect(decl).toContain("ComponentProps");
  });
});
